[platformio]
description="All the code for BYU's embedded controllers."
extra_configs =
    config/common.ini
    config/ecu_old.ini
    config/ecu.ini
    config/native.ini
default_envs = ecu_debug

[env]
test_framework = unity