[platformio]
description="All the code for BYU's embedded controllers."
extra_configs =
    config/common.ini
    config/dcf.ini
    config/ecu_old.ini
    config/ecu.ini
    config/native_tests.ini
    config/pid_sim.ini
    config/battery_charger.ini
default_envs = ecu_not_rules_compliant

[env]
test_framework = unity