[common]
build_flags = -std=gnu++20
; This script generates a file containing the hash id and name of
; whoever uploaded the code.
extra_scripts = pre:scripts/gen_git_info.py
; List of flags applied to _our_ code only, not dependency code.
build_src_flags = -Wall -Wextra -Wpedantic
